#!/usr/bin/env python3
"""Compute the time correlator sum_T jpx(t)*jpx(t+T), averaged over all t, for
a single lattice mode (nkx, nky, nkz) from the raw jpx_re.dat/jpx_im.dat
snapshot files of one or more run directories, where each row is one time
step and each column is a lattice mode idx = nkx*Ny*Nzh + nky*Nzh + nkz with
Nzh = Nz//2 + 1 (FFTW's r2c layout: nkx slowest, the halved dimension nkz
fastest). Requested modes with nkz > Nz//2 are not stored explicitly; they
are read via Hermitian symmetry as the conjugate of the mode
(-nkx mod Nx, -nky mod Ny, Nz-nkz).

Run directories are expected to be named as generated by sim, e.g.
sim-Nx8Ny8Nz8dt0.1eta0.1Lam1.25seed327271822; Nx, Ny, Nz and dt are parsed
from the name. Unless --output-dir is passed, each correlator is written to
a directory named like the run but with "sim" replaced by "obs" and the seed
stripped (e.g. obs-Nx8Ny8Nz8dt0.1eta0.1Lam1.25). A trailing "x" suffix on the
run name (written by sim for --no-ideal-step runs) is kept, so such runs go
to obs-...x.

For each run directory, writes a file <output-dir>/<run_name>.dat with
columns time_diff, Re, Im (and a header recording nx, ny, nz, nkx, nky, nkz,
dt), so that plot_jpx_time_correlator.py can read the correlators back
without recomputing them."""

import argparse
import re
from pathlib import Path

import numpy as np

FLOAT = r"[0-9.]+(?:[eE][+-]?[0-9]+)?"
RUN_NAME_RE = re.compile(
    rf"sim-Nx(?P<nx>\d+)Ny(?P<ny>\d+)Nz(?P<nz>\d+)"
    rf"dt(?P<dt>{FLOAT})eta(?P<eta>{FLOAT})Lam(?P<lam>{FLOAT})"
    rf"seed(?P<seed>\d+)(?P<suffix>x?)$"
)


def parse_run_name(run_dir: Path) -> dict:
    m = RUN_NAME_RE.match(run_dir.name)
    if m is None:
        raise SystemExit(f"Cannot parse run directory name '{run_dir.name}': "
                         "expected the form sim-Nx8Ny8Nz8dt0.1eta0.1Lam1.25seed123")
    return {"nx": int(m["nx"]), "ny": int(m["ny"]), "nz": int(m["nz"]),
            "dt": float(m["dt"]),
            "obs_dir": Path(re.sub(r"^sim", "obs",
                                   re.sub(r"seed\d+(x?)$", r"\1", run_dir.name)))}


def load_mode(re_path: Path, im_path: Path, nkx: int, nky: int, nkz: int,
              nx: int, ny: int, nz: int) -> np.ndarray:
    nzh = nz // 2 + 1
    nkx %= nx
    nky %= ny
    nkz %= nz
    # The r2c layout only stores nkz = 0..nz//2; modes in the upper half are
    # the Hermitian conjugates F(nkx,nky,nkz) = conj(F(-nkx,-nky,nz-nkz)).
    conjugate = nkz >= nzh
    if conjugate:
        nkx = (nx - nkx) % nx
        nky = (ny - nky) % ny
        nkz = nz - nkz
    idx = nkx * ny * nzh + nky * nzh + nkz
    re = np.loadtxt(re_path, usecols=idx)
    im = np.loadtxt(im_path, usecols=idx)
    mode = re + 1j * im
    return np.conj(mode) if conjugate else mode


def time_correlator(jpx: np.ndarray) -> np.ndarray:
    n = len(jpx)
    correlator = np.empty(len(jpx), dtype=complex)
    for T in range(n):
        correlator[T] = np.mean(np.conj(jpx[:n - T]) * jpx[T:])
    # for n in range(len(jpx)):
    #     for m in range(len(jpx)-n):
    #         correlator[n] += np.conj(jpx[n+m]) * jpx[m]#
    #     correlator[n] /= (len(jpx)-n)
    return correlator


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-dirs", type=Path, nargs="+", required=True,
                         help="One or more run directories, each containing its own "
                              "jpx_re.dat, jpx_im.dat, named as generated by sim "
                              "(e.g. sim-Nx8Ny8Nz8dt0.1eta0.1Lam1.25seed123)")
    parser.add_argument("--nkx", type=int, required=True, help="kx mode index")
    parser.add_argument("--nky", type=int, required=True, help="ky mode index")
    parser.add_argument("--nkz", type=int, required=True, help="kz mode index")
    parser.add_argument("--output-dir", type=Path, default=None,
                         help="Directory to write the computed correlators into "
                              "(default: run dir name with 'sim' replaced by 'obs' "
                              "and the seed stripped)")
    args = parser.parse_args()

    for run_dir in args.run_dirs:
        params = parse_run_name(run_dir)

        output_dir = args.output_dir if args.output_dir is not None else params["obs_dir"]
        output_dir.mkdir(parents=True, exist_ok=True)

        header = (f"nx={params['nx']} ny={params['ny']} nz={params['nz']} "
                  f"nkx={args.nkx} nky={args.nky} nkz={args.nkz} dt={params['dt']}\n"
                  "time_diff Re Im")

        jpx = load_mode(run_dir / "jpx_re.dat", run_dir / "jpx_im.dat",
                         args.nkx, args.nky, args.nkz,
                         params["nx"], params["ny"], params["nz"])
        correlator = time_correlator(jpx)
        time_diff = np.arange(len(correlator)) * params["dt"]

        out_path = output_dir / f"{run_dir.name}.dat"
        np.savetxt(out_path,
                   np.column_stack([time_diff, correlator.real, correlator.imag]),
                   header=header)
        print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
