#!/usr/bin/env python3
"""Compute the time correlator sum_T jpx(t)*jpx(t+T), averaged over all t, for
a single lattice mode (nkx, nky, nkz) from the raw jpx_re.dat/jpx_im.dat
snapshot files of one or more run directories, where each row is one time
step and each column is a lattice mode idx = nkx*Ny*Nzh + nky*Nzh + nkz with
Nzh = Nz//2 + 1 (FFTW's r2c layout: nkx slowest, the halved dimension nkz
fastest).

Run directories are expected to be named as generated by sim, e.g.
sim-Nx8Ny8Nz8dt0.1eta0.1Lam1.25seed327271822; Nx, Ny, Nz and dt are parsed
from the name. Unless --output-dir is passed, each correlator is written to
a directory named like the run but with "sim" replaced by "obs" and the seed
stripped (e.g. obs-Nx8Ny8Nz8dt0.1eta0.1Lam1.25). A trailing "x" suffix on the
run name (written by sim for --no-ideal-step runs) is kept, so such runs go
to obs-...x.

For each run directory, writes a file <output-dir>/<run_name>.dat with
columns time_diff, Re, Im (and a header recording nx, ny, nz, nkx, nky, nkz,
dt), so that plot_jpx_time_correlator.py can read the correlators back
without recomputing them."""

import argparse
import re
from pathlib import Path

import numpy as np

FLOAT = r"[0-9.]+(?:[eE][+-]?[0-9]+)?"
RUN_NAME_RE = re.compile(
    rf"sim-Nx(?P<nx>\d+)Ny(?P<ny>\d+)Nz(?P<nz>\d+)"
    rf"dt(?P<dt>{FLOAT})eta(?P<eta>{FLOAT})Lam(?P<lam>{FLOAT})"
    rf"seed(?P<seed>\d+)(?P<suffix>x?)$"
)


def parse_run_name(run_dir: Path) -> dict:
    m = RUN_NAME_RE.match(run_dir.name)
    if m is None:
        raise SystemExit(f"Cannot parse run directory name '{run_dir.name}': "
                         "expected the form sim-Nx8Ny8Nz8dt0.1eta0.1Lam1.25seed123")
    return {"nx": int(m["nx"]), "ny": int(m["ny"]), "nz": int(m["nz"]),
            "dt": float(m["dt"]),
            "obs_dir": Path(re.sub(r"^sim", "obs",
                                   re.sub(r"seed\d+(x?)$", r"\1", run_dir.name)))}


def load_mode(re_path: Path, im_path: Path, nkx: int, nky: int, nkz: int,
              ny: int, nzh: int) -> np.ndarray:
    idx = nkx * ny * nzh + nky * nzh + nkz
    re = np.loadtxt(re_path, usecols=idx)
    im = np.loadtxt(im_path, usecols=idx)
    return re + 1j * im


def time_correlator(jpi: np.ndarray) -> np.ndarray:
    n = len(jpi)
    correlator = np.empty(n, dtype=complex)
    for T in range(n):
        correlator[T] = np.mean(np.conj(jpi[:n - T]) * jpi[T:])
    return correlator


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-dirs", type=Path, nargs="+", required=True,
                         help="One or more run directories, each containing its own "
                              "jpx_re.dat, jpx_im.dat, named as generated by sim "
                              "(e.g. sim-Nx8Ny8Nz8dt0.1eta0.1Lam1.25seed123)")
    parser.add_argument("--nk", type=int, required=True, help="k mode index")
    parser.add_argument("--output-dir", type=Path, default=None,
                         help="Directory to write the computed correlators into "
                              "(default: run dir name with 'sim' replaced by 'obs' "
                              "and the seed stripped)")
    args = parser.parse_args()

    for run_dir in args.run_dirs:
        params = parse_run_name(run_dir)
        nzh = params["nz"] // 2 + 1

        nx = params['nx']
        ny = params['ny']
        nz = params['nz']
        assert nx==ny==nz, f"Expected isotropic lattice, got nx={nx}, ny={ny}, nz={nz}"

        output_dir = args.output_dir if args.output_dir is not None else params["obs_dir"]
        output_dir.mkdir(parents=True, exist_ok=True)

        header = (f"nx={nx} ny={ny} nz={nz} "
                  f"nk={args.nk} dt={params['dt']}\n"
                  "time_diff Re Im")

        jpx_y1 = load_mode(run_dir / "jpx_re.dat", run_dir / "jpx_im.dat",
                         0, args.nk, 0, params["ny"], nzh)
        jpx_y2 = load_mode(run_dir / "jpx_re.dat", run_dir / "jpx_im.dat",
                         0, params["ny"] - args.nk, 0, params["ny"], nzh)
        
        jpx_z1 = load_mode(run_dir / "jpx_re.dat", run_dir / "jpx_im.dat",
                         0, 0, args.nk, params["ny"], nzh)
        jpx_z2 = load_mode(run_dir / "jpx_re.dat", run_dir / "jpx_im.dat",
                         0, 0, params["nz"] - args.nk, params["ny"], nzh)
        
        jpy_x1 = load_mode(run_dir / "jpy_re.dat", run_dir / "jpy_im.dat",
                         args.nk, 0, 0, params["ny"], nzh)
        jpy_x2 = load_mode(run_dir / "jpy_re.dat", run_dir / "jpy_im.dat",
                         params["nx"] - args.nk, 0, 0, params["ny"], nzh)
        
        jpy_z1 = load_mode(run_dir / "jpy_re.dat", run_dir / "jpy_im.dat",
                         0, 0, args.nk, params["ny"], nzh)
        jpy_z2 = load_mode(run_dir / "jpy_re.dat", run_dir / "jpy_im.dat",
                         0, 0, params["nz"] - args.nk, params["ny"], nzh)

        jpz_x1 = load_mode(run_dir / "jpz_re.dat", run_dir / "jpz_im.dat",
                            args.nk, 0, 0, params["ny"], nzh)
        jpz_x2 = load_mode(run_dir / "jpz_re.dat", run_dir / "jpz_im.dat",
                            params["nx"] - args.nk, 0, 0, params["ny"], nzh)
        
        jpz_y1 = load_mode(run_dir / "jpz_re.dat", run_dir / "jpz_im.dat",
                         0, args.nk, 0, params["ny"], nzh)
        jpz_y2 = load_mode(run_dir / "jpz_re.dat", run_dir / "jpz_im.dat",
                         0, params["ny"] - args.nk, 0, params["ny"], nzh)
        
        corr_jpx_y1 = time_correlator(jpx_y1)
        corr_jpx_y2 = time_correlator(jpx_y2)
        corr_jpx_z1 = time_correlator(jpx_z1)
        corr_jpx_z2 = time_correlator(jpx_z2)

        corr_jpy_x1 = time_correlator(jpy_x1)
        corr_jpy_x2 = time_correlator(jpy_x2)
        corr_jpy_z1 = time_correlator(jpy_z1)
        corr_jpy_z2 = time_correlator(jpy_z2)

        corr_jpz_x1 = time_correlator(jpz_x1)
        corr_jpz_x2 = time_correlator(jpz_x2)
        corr_jpz_y1 = time_correlator(jpz_y1)
        corr_jpz_y2 = time_correlator(jpz_y2)

        # Sum all of them and divide by twelve to get the average correlator
        correlator = (corr_jpx_y1 + corr_jpx_y2 + corr_jpx_z1 + corr_jpx_z2 +
                      corr_jpy_x1 + corr_jpy_x2 + corr_jpy_z1 + corr_jpy_z2 +
                      corr_jpz_x1 + corr_jpz_x2 + corr_jpz_y1 + corr_jpz_y2) / 12.0

        time_diff = np.arange(len(corr_jpx_y1)) * params["dt"]

        out_path = output_dir / f"{run_dir.name}.dat"
        np.savetxt(out_path,
                   np.column_stack([time_diff, correlator.real, correlator.imag]),
                   header=header)
        print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
