#!/usr/bin/env python3
"""Compute the time correlator sum_T conj(djpx/dt(t))*djpx/dt(t+T) of the time
derivative of the current, averaged over all modes and t, for a fixed mode
magnitude nk from the raw jpx_re.dat/jpx_im.dat, jpy_re.dat/jpy_im.dat and
jpz_re.dat/jpz_im.dat snapshot files of one or more run directories, where
each row is one time step and each column is a lattice mode
idx = nkx*Ny*Nzh + nky*Nzh + nkz with Nzh = Nz//2 + 1 (FFTW's r2c layout:
nkx slowest, the halved dimension nkz fastest).

This is the same quantity as computed by compute_avg_jp_time_correlator.py,
but with every mode series jp(t,p) replaced by its time derivative
djp(t,p)/dt before the correlator is taken; at T=0 it reduces to the
equal-time average < |djp/dt|^2 > the shorthand < (djp*/dt)(djp/dt) > refers
to. The derivative is taken with np.gradient at the snapshot spacing dt, and
the first and last sample are dropped afterwards so that every remaining
value comes from the same centred difference and the series stays homogeneous
in t. Note that the derivative correlator is far more sensitive to the
snapshot spacing than the correlator itself, so compare runs at equal dt or
check the dt dependence explicitly.

Run directories are expected to be named as generated by sim, e.g.
sim-Nx8Ny8Nz8dt0.1eta0.1Lam1.25seed327271822; Nx, Ny, Nz and dt are parsed
from the name. Unless --output-dir is passed, each correlator is written to
a directory named like the run but with "sim" replaced by "avg-jpdot-time-corr",
the seed stripped and the mode index appended
(e.g. avg-jpdot-time-corr-Nx8Ny8Nz8dt0.1eta0.1Lam1.25nk7 for --nk 7). A
trailing "x" suffix on the run name (written by sim for --no-ideal-step runs)
is kept at the very end, so such runs go to avg-jpdot-time-corr-...nk7x.

Runs that were interrupted (or are still running) end in a partially written
row; such rows are ignored, and all modes are truncated to the time steps that
are complete in every file.

For each run directory, writes a file <output-dir>/<run_name>.dat with
columns time_diff, Re, Im (and a header recording nx, ny, nz, nk, dt), in the
same format as compute_avg_jp_time_correlator.py."""

import argparse
import re
from pathlib import Path

import numpy as np

FLOAT = r"[0-9.]+(?:[eE][+-]?[0-9]+)?"
RUN_NAME_RE = re.compile(
    rf"sim-Nx(?P<nx>\d+)Ny(?P<ny>\d+)Nz(?P<nz>\d+)"
    rf"dt(?P<dt>{FLOAT})eta(?P<eta>{FLOAT})Lam(?P<lam>{FLOAT})"
    rf"seed(?P<seed>\d+)(?P<suffix>x?)$"
)


def parse_run_name(run_dir: Path) -> dict:
    m = RUN_NAME_RE.match(run_dir.name)
    if m is None:
        raise SystemExit(f"Cannot parse run directory name '{run_dir.name}': "
                         "expected the form sim-Nx8Ny8Nz8dt0.1eta0.1Lam1.25seed123")
    return {"nx": int(m["nx"]), "ny": int(m["ny"]), "nz": int(m["nz"]),
            "dt": float(m["dt"]), "suffix": m["suffix"],
            "out_base": re.sub(r"^sim", "avg-jpdot-time-corr",
                               re.sub(r"seed\d+x?$", "", run_dir.name))}


def complete_rows(path: Path, ncols: int):
    """Yield the rows of path that contain all ncols values.

    sim writes one space after every value, so a complete row contains exactly
    ncols spaces. A run that was killed while writing (or that is still
    running) leaves a partially written final row, which np.loadtxt would
    reject with "invalid column index ... with N columns"; stop at the first
    such row instead."""
    with open(path) as f:
        for lineno, line in enumerate(f, 1):
            nvalues = line.count(" ")
            if nvalues != ncols:
                print(f"warning: {path}: row {lineno} holds {nvalues} of "
                      f"{ncols} values, ignoring it and everything after it")
                return
            yield line


def mode_index(nkx: int, nky: int, nkz: int,
               nx: int, ny: int, nz: int) -> tuple:
    """Column index of the mode (nkx, nky, nkz), and whether the stored value
    has to be conjugated to obtain it."""
    nzh = nz // 2 + 1
    nkx %= nx
    nky %= ny
    nkz %= nz
    # The r2c layout only stores nkz = 0..nz//2; modes in the upper half are
    # the Hermitian conjugates F(nkx,nky,nkz) = conj(F(-nkx,-nky,nz-nkz)).
    conjugate = nkz >= nzh
    if conjugate:
        nkx = (nx - nkx) % nx
        nky = (ny - nky) % ny
        nkz = nz - nkz
    return nkx * ny * nzh + nky * nzh + nkz, conjugate


def load_modes(re_path: Path, im_path: Path, modes: list,
               nx: int, ny: int, nz: int) -> list:
    """Load the given (nkx, nky, nkz) modes, reading each file only once.

    The returned series are truncated to the rows that are complete in both the
    real and the imaginary part file."""
    ncols = nx * ny * (nz // 2 + 1)
    specs = [mode_index(nkx, nky, nkz, nx, ny, nz) for nkx, nky, nkz in modes]
    cols = sorted({idx for idx, _ in specs})
    re_cols = np.loadtxt(complete_rows(re_path, ncols),
                         usecols=cols).reshape(-1, len(cols))
    im_cols = np.loadtxt(complete_rows(im_path, ncols),
                         usecols=cols).reshape(-1, len(cols))
    n = min(len(re_cols), len(im_cols))
    col_of = {idx: i for i, idx in enumerate(cols)}

    loaded = []
    for idx, conjugate in specs:
        mode = re_cols[:n, col_of[idx]] + 1j * im_cols[:n, col_of[idx]]
        loaded.append(np.conj(mode) if conjugate else mode)
    return loaded


def time_derivative(jpi: np.ndarray, dt: float) -> np.ndarray:
    """d jpi/dt on the snapshot grid, from centred differences only.

    np.gradient closes the series with one-sided differences at both ends;
    those two samples are dropped so that the correlator below averages over
    values that were all obtained the same way."""
    if len(jpi) < 3:
        raise SystemExit("need at least 3 time steps to take a time derivative")
    return np.gradient(jpi, dt)[1:-1]


def time_correlator(jpi: np.ndarray) -> np.ndarray:
    n = len(jpi)
    correlator = np.empty(n, dtype=complex)
    for T in range(n):
        correlator[T] = np.mean(np.conj(jpi[:n - T]) * jpi[T:])
    return correlator


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-dirs", type=Path, nargs="+", required=True,
                         help="One or more run directories, each containing its own "
                              "jpx_re.dat, jpx_im.dat, named as generated by sim "
                              "(e.g. sim-Nx8Ny8Nz8dt0.1eta0.1Lam1.25seed123)")
    parser.add_argument("--nk", type=int, required=True, help="k mode index")
    parser.add_argument("--output-dir", type=Path, default=None,
                         help="Directory to write the computed correlators into "
                              "(default: run dir name with 'sim' replaced by 'avg-jpdot-time-corr', "
                              "the seed stripped and nk<N> appended)")
    args = parser.parse_args()

    nk = args.nk

    for run_dir in args.run_dirs:
        params = parse_run_name(run_dir)

        nx = params['nx']
        ny = params['ny']
        nz = params['nz']
        assert nx==ny==nz, f"Expected isotropic lattice, got nx={nx}, ny={ny}, nz={nz}"

        output_dir = (args.output_dir if args.output_dir is not None
                      else Path(f"{params['out_base']}nk{nk}{params['suffix']}"))
        output_dir.mkdir(parents=True, exist_ok=True)

        header = (f"nx={nx} ny={ny} nz={nz} "
                  f"nk={nk} dt={params['dt']}\n"
                  "time_diff Re Im")

        # For each component, the two transverse directions and both signs of k.
        jpx_modes = load_modes(run_dir / "jpx_re.dat", run_dir / "jpx_im.dat",
                               [(0, nk, 0), (0, -nk, 0),
                                (0, 0, nk), (0, 0, -nk)], nx, ny, nz)
        jpy_modes = load_modes(run_dir / "jpy_re.dat", run_dir / "jpy_im.dat",
                               [(nk, 0, 0), (-nk, 0, 0),
                                (0, 0, nk), (0, 0, -nk)], nx, ny, nz)
        jpz_modes = load_modes(run_dir / "jpz_re.dat", run_dir / "jpz_im.dat",
                               [(nk, 0, 0), (-nk, 0, 0),
                                (0, nk, 0), (0, -nk, 0)], nx, ny, nz)

        modes = jpx_modes + jpy_modes + jpz_modes

        # jpx, jpy and jpz are written one after the other, so an interrupted
        # run can leave one file a time step shorter than the others.
        n_steps = min(len(mode) for mode in modes)
        if n_steps == 0:
            raise SystemExit(f"{run_dir}: no complete time steps found")
        if n_steps != max(len(mode) for mode in modes):
            print(f"{run_dir}: files differ in length, using the first "
                  f"{n_steps} time steps")
        modes = [mode[:n_steps] for mode in modes]

        # Differentiate first, then correlate: the two endpoints time_derivative
        # drops cost the series two time steps.
        derivs = [time_derivative(mode, params["dt"]) for mode in modes]
        n_deriv = n_steps - 2

        # Average the correlator over all twelve transverse modes
        correlator = sum(time_correlator(deriv) for deriv in derivs) / len(derivs)

        time_diff = np.arange(n_deriv) * params["dt"]

        out_path = output_dir / f"{run_dir.name}.dat"
        np.savetxt(out_path,
                   np.column_stack([time_diff, correlator.real, correlator.imag]),
                   header=header)
        print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
