#!/usr/bin/env python3
"""Plot the logarithmic time derivative d ln f(t)/dt = f'(t)/f(t) of the real
part f(t) of the time correlator sum_T jpx(t)*jpx(t+T) as a function of the
time difference t, averaged over several runs with an error band from their
run-to-run variation. For an exponential decay f(t) ~ exp(-Gamma t) this is
the constant -Gamma. Only meaningful at small t, before f(t) decays into the
noise; restrict the view with --xlim/--ylim.

Reads the per-run correlator files written by compute_jpx_time_correlator.py:
one <run>.dat file per run in --input-dir, with columns time_diff, Re, Im and
a header recording nx, ny, nz, nkx, nky, nkz, dt for the given mode.

Each input directory is expected to be named as generated by
compute_jpx_time_correlator.py, e.g. obs-Nx8Ny8Nz8dt0.1eta0.1Lam1.25 (with an
optional trailing "x" for --no-ideal-step runs); the shear viscosity eta is
parsed from that name. With several directories, the log-derivatives of
all of them are drawn into the same plot. For each directory the theory
expectation is drawn as two horizontal lines, -(eta/rho)(1+eta_reg_uv)k_hat^2
with the bare (dashed) and the renormalized (dotted) shear viscosity, and the
corresponding correlation times 1/Gamma as two vertical lines.

The t axis is scaled by the bare correlation time of the mode,
tau = rho/(eta (1+eta_reg_uv) k_hat^2), so that the bare exponential decay
reaches 1/e at t/tau = 1 for every eta and k and curves from different
directories can be compared directly. Time arguments (fit and plateau
windows) stay in units of t; only the axis is scaled."""

import argparse
import re
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

import plot_style
from rfrg_coefficients import coefficients

plot_style.use()

AUTO_OUTPUT = Path("<auto>")

FLOAT = r"[0-9.]+(?:[eE][+-]?[0-9]+)?"
OBS_NAME_RE = re.compile(
    rf"obs-Nx(?P<nx>\d+)Ny(?P<ny>\d+)Nz(?P<nz>\d+)"
    rf"dt(?P<dt>{FLOAT})eta(?P<eta>{FLOAT})Lam(?P<lam>{FLOAT})(?P<suffix>x?)$"
)


def parse_obs_name(input_dir: Path) -> dict:
    m = OBS_NAME_RE.match(input_dir.name)
    if m is None:
        raise SystemExit(f"Cannot parse input directory name '{input_dir.name}': "
                         "expected the form obs-Nx8Ny8Nz8dt0.1eta0.1Lam1.25")
    return {"nx": int(m["nx"]), "ny": int(m["ny"]), "nz": int(m["nz"]),
            "dt": float(m["dt"]), "eta": float(m["eta"]), "lam": float(m["lam"])}


def lattice_label(nx: int, ny: int, nz: int) -> str:
    r"""LaTeX for the lattice size: $32^3$ for a cubic lattice, $32^2 \times 10$
    when one direction differs from the two others."""
    dims = (nx, ny, nz)
    if nx == ny == nz:
        return rf"${nx}^3$"
    for d in dims:
        if dims.count(d) == 2:
            odd = next(o for o in dims if o != d)
            return rf"${d}^2 \times {odd}$"
    return rf"${nx} \times {ny} \times {nz}$"


def label_hline(axis, y, text, color, x=0.01, below=False):
    """Label a horizontal theory line next to the line itself instead of in
    the legend: at the left edge of the axes, just above (or below) the
    line. x is a fraction of the axes width, y a data coordinate."""
    axis.annotate(text, xy=(x, y), xycoords=axis.get_yaxis_transform(),
                  xytext=(0, -3 if below else 3), textcoords="offset points",
                  ha="left" if x < 0.5 else "right",
                  va="top" if below else "bottom",
                  color=color, fontsize="small")


def label_vline(axis, x, text, color, y=0.02, on_left=True):
    """Label a vertical theory line next to the line itself instead of in the
    legend: rotated along the line, near the bottom of the axes, on its
    right (on_left) or on its left. x is a data coordinate, y a fraction
    of the axes height."""
    axis.annotate(text, xy=(x, y), xycoords=axis.get_xaxis_transform(),
                  xytext=(5, 0) if on_left else (-5, 0), textcoords="offset points", rotation=90,
                  ha="left" if on_left else "right", va="bottom",
                  color=color, fontsize="small")


def legend_label(input_dir: Path) -> str:
    r"""Legend entry for one directory, e.g.
    "$32^3$, dt = 10, $\eta = 0.0707107$, $\Lambda = 0.4$".

    The numbers are taken verbatim from the directory name, so the legend
    shows exactly what the run used; --no-ideal-step runs are marked as such,
    which is all that distinguishes them from their ideal-step counterpart."""
    m = OBS_NAME_RE.match(input_dir.name)
    label = (f"{lattice_label(int(m['nx']), int(m['ny']), int(m['nz']))}, "
             #f"dt = {m['dt']}, "
             rf"$\eta = {m['eta']}$, $a\Lambda = {m['lam']}$")
    if m["suffix"] == "x":
        label += ", no ideal step"
    return label


def read_header(path: Path) -> dict:
    with open(path) as f:
        first_line = f.readline().lstrip("#").strip()
    return {key: float(value) for key, value in
            (item.split("=") for item in first_line.split())}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input_dirs", type=Path, nargs="+",
                         help="One or more directories containing the *.dat correlator "
                              "files written by compute_jpx_time_correlator.py, named "
                              "like obs-Nx8Ny8Nz8dt0.1eta0.1Lam1.25 (eta is "
                              "parsed from the name); all are drawn into the same plot")
    parser.add_argument("--mass-density", type=float, default=1.0, help="Mass density")
    parser.add_argument("--temp", type=float, default=1.0, help="Temperature")
    parser.add_argument("--plateau-window", type=float, nargs=2, default=None,
                         metavar=("T1", "T2"),
                         help="Average the log-derivative per run over this time "
                              "window (chosen where the curve is flat: after the "
                              "early transient, before the correlator decays into "
                              "the noise), convert it to the renormalized shear "
                              "viscosity etaR = -<dln Re/dt>/(k_hat^2 "
                              "(1+eta_reg_uv)/rho), print etaR +- SEM, and draw "
                              "the window and plateau level in the plot; given "
                              "in units of t, not of the scaled x axis")
    parser.add_argument("-o", "--output", type=Path, nargs="?", default=None,
                         const=AUTO_OUTPUT,
                         help="Save the plot to this file instead of showing it; "
                              "without an argument, save to figs/<first-input-dir-name>.pdf "
                              "(with -cmp<n> appended when several input dirs are given)")
    parser.add_argument("--xlim", type=float, nargs=2, default=None,
                         metavar=("XMIN", "XMAX"),
                         help="x-axis limits of the plot, in units of the bare "
                              "correlation time")
    parser.add_argument("--ylim", type=float, nargs=2, default=None,
                         metavar=("YMIN", "YMAX"),
                         help="y-axis limits of the plot, in units of the bare "
                              "damping rate 1/tau (the bare theory sits at -1)")
    parser.add_argument("--xlog", action="store_true",
                         help="Use a logarithmic x-axis")
    parser.add_argument("--ylog", action="store_true",
                         help="Use a logarithmic y-axis")
    args = parser.parse_args()

    if args.output is AUTO_OUTPUT:
        stem = args.input_dirs[0].name.replace("obs-", "obs-deriv-")
        if len(args.input_dirs) > 1:
            stem += f"-cmp{len(args.input_dirs) - 1}"
        args.output = Path("figs") / f"{stem}.pdf"
        args.output.parent.mkdir(exist_ok=True)

    single = len(args.input_dirs) == 1
    fig, ax = plt.subplots()
    modes = []
    plateau_spans = []
    for input_dir in args.input_dirs:
        obs_name = parse_obs_name(input_dir)
        eta = obs_name["eta"]
        lam = obs_name["lam"]

        paths = sorted(input_dir.glob("*.dat"))
        if not paths:
            raise SystemExit(f"No correlator files found in {input_dir}")

        meta = read_header(paths[0])
        modes.append((meta["nkx"], meta["nky"], meta["nkz"]))

        def eta_reg_uv(k2):
            x = k2/(lam*lam)
            if x > 1:
                return x - 1
            else:
                return 0

        kx = 2.0*np.sin(2 * np.pi * meta["nkx"] / meta["nx"] * 0.5)
        ky = 2.0*np.sin(2 * np.pi * meta["nky"] / meta["ny"] * 0.5)
        kz = 2.0*np.sin(2 * np.pi * meta["nkz"] / meta["nz"] * 0.5)
        k2 = kx**2 + ky**2 + kz**2
        damp_per_eta = (1+eta_reg_uv(k2)) / args.mass_density * k2
        damp = eta * damp_per_eta
        # The time axis is scaled by the bare correlation time of the mode,
        # tau_bare = 1/damp = rho/(eta (1+eta_reg_uv) k_hat^2), so that the
        # bare exponential decays as exp(-t/tau_bare) whatever eta and k are.
        tau_bare = 1.0/damp

        dim = 2 if meta["nz"] == 1 else 3
        coeff1, coeff2, coeff_inf = coefficients(dim)
        etaR1 = np.sqrt(eta**2 + 2.0*coeff1*args.temp*args.mass_density*lam)
        etaR2 = np.sqrt(eta**2 + 2.0*coeff2*args.temp*args.mass_density*lam)
        dampR1 = etaR1 * damp_per_eta
        dampR2 = etaR2 * damp_per_eta
        if coeff_inf is not None:
            etaR_inf = np.sqrt(eta**2 + 2.0*coeff_inf*args.temp*args.mass_density*lam)
            dampR_inf = etaR_inf * damp_per_eta

        # Per-run log-derivative f'/f, then mean and SEM across runs. Only valid
        # at small t: once a run's f(t) decays into the noise and crosses zero,
        # its f'/f blows up and mean and SEM become meaningless.
        log_derivatives = []
        time_diff = None
        for path in paths:
            t, re_part, im_part = np.loadtxt(path, unpack=True)
            if time_diff is None:
                time_diff = t
            log_derivatives.append(np.gradient(re_part, t) / re_part)

        n_min = min(len(d) for d in log_derivatives)
        log_derivatives = np.stack([d[:n_min] for d in log_derivatives])
        time_diff = time_diff[:n_min]
        t_scaled = time_diff/tau_bare

        mean = log_derivatives.mean(axis=0)
        n_runs = len(log_derivatives)
        if n_runs > 1:
            sem = log_derivatives.std(axis=0, ddof=1) / np.sqrt(n_runs)
        else:
            sem = np.zeros(n_min)

        if single:
            label = r"$\tau\,\partial_t \ln \mathrm{Re}$"
        else:
            label = legend_label(input_dir)
        # The log-derivative is scaled by the same tau_bare as the time
        # axis, so it is d ln f/d(t/tau_bare): the bare rate sits at -1 and
        # the renormalized one at -etaR/eta, whatever eta and k are.
        line, = ax.plot(t_scaled, mean*tau_bare, label=label)
        ax.fill_between(t_scaled, (mean - sem)*tau_bare, (mean + sem)*tau_bare,
                         color=line.get_color(), alpha=0.3)

        first = input_dir is args.input_dirs[0]
        # Scaled by tau_bare, the bare rate sits at -1 and the bare
        # correlation time at 1 for every directory, so those two lines are
        # common to all of them: draw them once, in a color of their own
        # rather than in one directory's.
        # Theory is black, whatever the directory: the colors of the plot
        # identify the data, and a theory line belongs to none of them in
        # particular. Bare and renormalized are told apart by their line
        # style and by the labels next to them.
        theory_color = "black"
        # The theory lines carry their label inside the plot, next to the
        # line itself, so that they do not crowd out the data in the legend.
        # Only the first directory labels them: the theory lines of several
        # directories coincide or lie close together, so one label each is
        # enough.
        #if first:
        #    ax.axhline(-1.0, linestyle="--", color=theory_color, alpha=0.7)
        #    ax.axvline(1.0, linestyle="--", color=theory_color, alpha=0.7)
        ax.axhspan(min(-dampR1, -dampR2)*tau_bare,
                   max(-dampR1, -dampR2)*tau_bare,
                   color=theory_color, alpha=0.3)
        ax.axvspan(min(1.0/dampR1, 1.0/dampR2)/tau_bare,
                   max(1.0/dampR1, 1.0/dampR2)/tau_bare,
                   color=theory_color, alpha=0.3)
        if coeff_inf is not None:
            ax.axhline(-dampR_inf*tau_bare, linestyle=":", color=theory_color,
                       alpha=0.7)
            ax.axvline(1.0/(dampR_inf*tau_bare), linestyle=":", color=theory_color,
                       alpha=0.7)
        if single or first:
            # label_hline(ax, -1.0, r"$-1$", theory_color)
            # Anchored at the upper edge of the band, above it.
            label_hline(ax, max(-dampR1, -dampR2)*tau_bare,
                        r"$-\eta_R/\eta$ (rFRG), $L$ finite",
                        theory_color)
            # label_vline(ax, 1.0, r"$1$", theory_color)
            label_vline(ax, max(1.0/dampR1, 1.0/dampR2)/tau_bare,
                        r"$\eta/\eta_R$ (rFRG), $L$ finite", theory_color, on_left=True)
            if coeff_inf is not None:
                label_hline(ax, -dampR_inf*tau_bare,
                            r"$-\eta_R/\eta$ (rFRG), $L=\infty$",
                            theory_color, below=True)
                label_vline(ax, 1.0/(dampR_inf*tau_bare),
                            r"$\eta/\eta_R$ (rFRG), $L=\infty$",
                            theory_color, on_left=False)

        if args.plateau_window is not None:
            t1, t2 = args.plateau_window
            sel = (time_diff >= t1) & (time_diff <= t2)
            if not sel.any():
                raise SystemExit(f"Plateau window [{t1}, {t2}] contains no "
                                 f"data points of {input_dir.name}")

            # Average the local rate per run over the window, then mean and
            # SEM across runs, so the error includes the correlated noise.
            per_run = log_derivatives[:, sel].mean(axis=1)
            rate = per_run.mean()
            if n_runs > 1:
                rate_sem = per_run.std(ddof=1) / np.sqrt(n_runs)
            else:
                rate_sem = 0.0
            etaR = -rate / damp_per_eta
            etaR_err = rate_sem / damp_per_eta
            print(f"{input_dir.name}: plateau [{t1:g}, {t2:g}]: "
                  f"etaR = {etaR:g} +- {etaR_err:g} (bare eta = {obs_name['eta']:g})")

            plateau_spans.append((t1/tau_bare, t2/tau_bare))
            ax.hlines(rate*tau_bare, t1/tau_bare, t2/tau_bare, color=line.get_color(),
                      linestyle="--",
                      label=r"$\eta_R = $" f"{etaR:.4g}"
                            r"$\,\pm\,$" f"{etaR_err:.2g}")

    # One span per directory: the same window in t is a different window in
    # t/tau_bare for every eta and k. Identical spans are drawn only once.
    for span in dict.fromkeys(plateau_spans):
        ax.axvspan(*span, color="gray", alpha=0.1, zorder=0)

    ax.set_xlabel(r"$t / \tau$,  $\tau = \rho/(\eta \hat{\mathbf{k}}^2)$")
    ylabel = r"$\tau\,\partial_t \ln \mathrm{Re}\,\frac{1}{T}\sum_T \langle j_{x}^{*}(T+t,\mathbf{k}) j_{x}(T,\mathbf{k})\rangle$"
    if len(set(modes)) == 1:
        ylabel += (r",  $\mathbf{k}=$"
                   f"({modes[0][0]:.0f}, {modes[0][1]:.0f}, {modes[0][2]:.0f})"
                   r"$\pi/N$")
    ax.set_ylabel(ylabel)
    if args.xlim is not None:
        ax.set_xlim(*args.xlim)
    if args.xlog:
        ax.set_xscale('log')
    if args.ylim is not None:
        ax.set_ylim(*args.ylim)
    if args.ylog:
        ax.set_yscale('log')
    # A fixed corner rather than "best": the theory labels sit inside the
    # plot, at the axes edges, and an automatically placed legend would
    # sooner or later be dropped on top of them.
    ax.legend(loc="lower right")
    fig.tight_layout(pad=0.2)

    if args.output is not None:
        fig.savefig(args.output)
    else:
        plt.show()


if __name__ == "__main__":
    main()
