#!/usr/bin/env python3
"""Plot the time correlator sum_T jpx(t)*jpx(t+T) as a function of the time
difference t, averaged over several runs with an error band from their
run-to-run variation.

Reads the per-run correlator files written by compute_jpx_time_correlator.py:
one <run>.dat file per run in --input-dir, with columns time_diff, Re, Im and
a header recording nx, ny, nz, nkx, nky, nkz, dt for the given mode.

Each input directory is expected to be named as generated by
compute_jpx_time_correlator.py, e.g. obs-Nx8Ny8Nz8dt0.1eta0.1Lam1.25 (with an
optional trailing "x" for --no-ideal-step runs); the shear viscosity eta is
parsed from that name. With a single directory, the real and imaginary
part are plotted; with several directories, all of them are drawn into the
same plot, each in its own color with the real part solid, the imaginary
part dash-dotted, and its own theory curves in the same color (dashed:
bare eta, dotted: renormalized eta). The correlation times
1/Gamma with Gamma = (eta/rho)(1+eta_reg_uv)k_hat^2 for the bare (dashed)
and the renormalized (dotted) shear viscosity are drawn as vertical lines.

The t axis is scaled by the bare correlation time of the mode,
tau = rho/(eta (1+eta_reg_uv) k_hat^2), so that the bare exponential decay
reaches 1/e at t/tau = 1 for every eta and k and curves from different
directories can be compared directly. Time arguments (fit and plateau
windows) stay in units of t; only the axis is scaled."""

import argparse
import re
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

from rfrg_coefficients import coefficients

AUTO_OUTPUT = Path("<auto>")

FLOAT = r"[0-9.]+(?:[eE][+-]?[0-9]+)?"
OBS_NAME_RE = re.compile(
    rf"obs-Nx(?P<nx>\d+)Ny(?P<ny>\d+)Nz(?P<nz>\d+)"
    rf"dt(?P<dt>{FLOAT})eta(?P<eta>{FLOAT})Lam(?P<lam>{FLOAT})(?P<suffix>x?)$"
)


def parse_obs_name(input_dir: Path) -> dict:
    m = OBS_NAME_RE.match(input_dir.name)
    if m is None:
        raise SystemExit(f"Cannot parse input directory name '{input_dir.name}': "
                         "expected the form obs-Nx8Ny8Nz8dt0.1eta0.1Lam1.25")
    return {"nx": int(m["nx"]), "ny": int(m["ny"]), "nz": int(m["nz"]),
            "dt": float(m["dt"]), "eta": float(m["eta"]), "lam": float(m["lam"])}


def lattice_label(nx: int, ny: int, nz: int) -> str:
    r"""LaTeX for the lattice size: $32^3$ for a cubic lattice, $32^2 \times 10$
    when one direction differs from the two others."""
    dims = (nx, ny, nz)
    if nx == ny == nz:
        return rf"${nx}^3$"
    for d in dims:
        if dims.count(d) == 2:
            odd = next(o for o in dims if o != d)
            return rf"${d}^2 \times {odd}$"
    return rf"${nx} \times {ny} \times {nz}$"


def legend_label(input_dir: Path) -> str:
    r"""Legend entry for one directory, e.g.
    "$32^3$, dt = 10, $\eta = 0.0707107$, $\Lambda = 0.4$".

    The numbers are taken verbatim from the directory name, so the legend
    shows exactly what the run used; --no-ideal-step runs are marked as such,
    which is all that distinguishes them from their ideal-step counterpart."""
    m = OBS_NAME_RE.match(input_dir.name)
    label = (f"{lattice_label(int(m['nx']), int(m['ny']), int(m['nz']))}, "
             f"dt = {m['dt']}, "
             rf"$\eta = {m['eta']}$, $\Lambda = {m['lam']}$")
    if m["suffix"] == "x":
        label += ", no ideal step"
    return label


def read_header(path: Path) -> dict:
    with open(path) as f:
        first_line = f.readline().lstrip("#").strip()
    return {key: float(value) for key, value in
            (item.split("=") for item in first_line.split())}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input_dirs", type=Path, nargs="+",
                         help="One or more directories containing the *.dat correlator "
                              "files written by compute_jpx_time_correlator.py, named "
                              "like obs-Nx8Ny8Nz8dt0.1eta0.1Lam1.25 (eta is "
                              "parsed from the name); all are drawn into the same plot")
    parser.add_argument("--mass-density", type=float, default=1.0, help="Mass density")
    parser.add_argument("--temp", type=float, default=1.0, help="Temperature")
    parser.add_argument("-o", "--output", type=Path, nargs="?", default=None,
                         const=AUTO_OUTPUT,
                         help="Save the plot to this file instead of showing it; "
                              "without an argument, save to figs/<first-input-dir-name>.pdf "
                              "(with -cmp<n> appended when several input dirs are given)")
    parser.add_argument("--xlim", type=float, nargs=2, default=None,
                         metavar=("XMIN", "XMAX"),
                         help="x-axis limits of the plot, in units of the bare "
                              "correlation time")
    parser.add_argument("--ylim", type=float, nargs=2, default=None,
                         metavar=("YMIN", "YMAX"),
                         help="y-axis limits of the plot")
    parser.add_argument("--xlog", action="store_true",
                         help="Use a logarithmic x-axis")
    parser.add_argument("--ylog", action="store_true",
                         help="Use a logarithmic y-axis")
    args = parser.parse_args()

    if args.output is AUTO_OUTPUT:
        stem = args.input_dirs[0].name
        if len(args.input_dirs) > 1:
            stem += f"-cmp{len(args.input_dirs) - 1}"
        args.output = Path("figs") / f"{stem}.pdf"
        args.output.parent.mkdir(exist_ok=True)

    single = len(args.input_dirs) == 1
    fig, ax = plt.subplots()
    modes = []
    for input_dir in args.input_dirs:
        obs_name = parse_obs_name(input_dir)
        eta = obs_name["eta"]
        lam = obs_name["lam"]

        paths = sorted(input_dir.glob("*.dat"))
        if not paths:
            raise SystemExit(f"No correlator files found in {input_dir}")

        meta = read_header(paths[0])
        modes.append((meta["nkx"], meta["nky"], meta["nkz"]))

        correlators = []
        time_diff = None
        for path in paths:
            t, re_part, im_part = np.loadtxt(path, unpack=True)
            if time_diff is None:
                time_diff = t
            correlators.append(re_part + 1j * im_part)

        n_min = min(len(c) for c in correlators)
        correlators = np.stack([c[:n_min] for c in correlators])
        time_diff = time_diff[:n_min]

        mean = correlators.mean(axis=0)
        n_runs = len(correlators)
        if n_runs > 1:
            # Standard error of the mean, not the run-to-run standard deviation:
            # the latter reflects the spread from the Langevin noise itself and
            # does not shrink as more runs are added, while the SEM quantifies
            # the uncertainty on the estimated mean correlator.
            sem_re = correlators.real.std(axis=0, ddof=1) / np.sqrt(n_runs)
            sem_im = correlators.imag.std(axis=0, ddof=1) / np.sqrt(n_runs)
        else:
            sem_re = np.zeros(n_min)
            sem_im = np.zeros(n_min)

        def eta_reg_uv(k2):
            x = k2/(lam*lam)
            if x > 1:
                return x - 1
            else:
                return 0

        kx = 2.0*np.sin(2 * np.pi * meta["nkx"] / meta["nx"] * 0.5)
        ky = 2.0*np.sin(2 * np.pi * meta["nky"] / meta["ny"] * 0.5)
        kz = 2.0*np.sin(2 * np.pi * meta["nkz"] / meta["nz"] * 0.5)
        k2 = kx**2 + ky**2 + kz**2
        damp = eta*(1+eta_reg_uv(k2)) / args.mass_density * k2
        # The time axis is scaled by the bare correlation time of the mode,
        # tau_bare = 1/damp = rho/(eta (1+eta_reg_uv) k_hat^2), so that the
        # bare exponential decays as exp(-t/tau_bare) whatever eta and k are.
        tau_bare = 1.0/damp
        t_scaled = time_diff/tau_bare

        nsites = meta["nx"] * meta["ny"] * meta["nz"]
        theory =  args.temp * args.mass_density* np.exp(-damp * time_diff)

        dim = 2 if meta["nz"] == 1 else 3
        coeff1, coeff2, coeff_inf = coefficients(dim)
        etaR1 = np.sqrt(eta**2 + 2.0*coeff1*args.temp*args.mass_density*lam)
        etaR2 = np.sqrt(eta**2 + 2.0*coeff2*args.temp*args.mass_density*lam)
        if coeff_inf is not None:
            etaR_inf = np.sqrt(eta**2 + 2.0*coeff_inf*args.temp*args.mass_density*lam)
            print("Renormalized eta: ", eta, " -> ", etaR1, "..", etaR2,
                  " (L=inf: ", etaR_inf, ")")
        else:
            print("Renormalized eta: ", eta, " -> ", etaR1, "..", etaR2)

        dampR1 = etaR1*(1+eta_reg_uv(k2)) / args.mass_density * k2
        dampR2 = etaR2*(1+eta_reg_uv(k2)) / args.mass_density * k2

        theoryR1 = args.temp * args.mass_density * np.exp(-dampR1 * time_diff)
        theoryR2 = args.temp * args.mass_density * np.exp(-dampR2 * time_diff)
        if coeff_inf is not None:
            dampR_inf = etaR_inf*(1+eta_reg_uv(k2)) / args.mass_density * k2
            theoryR_inf = args.temp * args.mass_density * np.exp(-dampR_inf * time_diff)

        if single:
            for part, values, errors in (("Re", mean.real, sem_re), ("Im", mean.imag, sem_im)):
                line, = ax.plot(t_scaled, values/nsites, label=part)
                ax.fill_between(t_scaled, (values - errors)/nsites, (values + errors)/nsites,
                                 color=line.get_color(), alpha=0.3)
            ax.plot(t_scaled, theory, "--", color="red",
                    label=r"$\exp(-(\eta/\rho) \, \hat{\mathbf{k}}^2\, t)$")
            ax.fill_between(t_scaled, theoryR1, theoryR2, color="black", alpha=0.3,
                            label=r"$\exp(-(\eta_R/\rho) \, \hat{\mathbf{k}}^2\, t)$")
            if coeff_inf is not None:
                ax.plot(t_scaled, theoryR_inf, "--", color="black", alpha=0.7,
                        label=r"$\exp(-(\eta_R/\rho) \, \hat{\mathbf{k}}^2\, t)$, $L=\infty$")
            ax.axvline(1.0, linestyle="--", color="red", alpha=0.7,
                       label=r"$\rho/(\eta \hat{\mathbf{k}}^2)$")
            ax.axvspan(min(1.0/dampR1, 1.0/dampR2)/tau_bare,
                   max(1.0/dampR1, 1.0/dampR2)/tau_bare,
                       color="black", alpha=0.3,
                       label=r"$\rho/(\eta_R \hat{\mathbf{k}}^2)$")
        else:
            first = input_dir is args.input_dirs[0]
            label = legend_label(input_dir)
            line, = ax.plot(t_scaled, mean.real/nsites, label=label)
            ax.fill_between(t_scaled, (mean.real - sem_re)/nsites,
                             (mean.real + sem_re)/nsites,
                             color=line.get_color(), alpha=0.3)
            ax.plot(t_scaled, mean.imag/nsites, "-.", color=line.get_color(), alpha=0.7,
                    label=r"$\mathrm{Im}$" if first else None)
            ax.fill_between(t_scaled, (mean.imag - sem_im)/nsites,
                             (mean.imag + sem_im)/nsites,
                             color=line.get_color(), alpha=0.2)
            ax.plot(t_scaled, theory, "--", color=line.get_color(), alpha=0.7,
                    label=r"$\exp(-(\eta/\rho) \, \hat{\mathbf{k}}^2\, t)$" if first else None)
            ax.fill_between(t_scaled, theoryR1, theoryR2, color=line.get_color(), alpha=0.3,
                            label=r"$\exp(-(\eta_R/\rho) \, \hat{\mathbf{k}}^2\, t)$" if first else None)
            if coeff_inf is not None:
                ax.plot(t_scaled, theoryR_inf, ":", color=line.get_color(), alpha=0.7,
                        label=r"$\exp(-(\eta_R/\rho) \, \hat{\mathbf{k}}^2\, t)$, $L=\infty$" if first else None)
            ax.axvline(1.0, linestyle="--", color=line.get_color(), alpha=0.7,
                       label=r"$\rho/(\eta \hat{\mathbf{k}}^2)$" if first else None)
            ax.axvspan(min(1.0/dampR1, 1.0/dampR2)/tau_bare,
                   max(1.0/dampR1, 1.0/dampR2)/tau_bare,
                       color=line.get_color(), alpha=0.3,
                       label=r"$\rho/(\eta_R \hat{\mathbf{k}}^2)$" if first else None)

    ax.set_xlabel(r"$t / \tau$,  $\tau = \rho/(\eta \hat{\mathbf{k}}^2)$")
    ylabel = r"$\frac{1}{T}\sum_T  \langle j_{x}^{*}(T+t,\mathbf{k}) j_{x}(T,\mathbf{k})\rangle$"
    if len(set(modes)) == 1:
        ylabel += (r",  $\mathbf{k}=$"
                   f"({modes[0][0]:.0f}, {modes[0][1]:.0f}, {modes[0][2]:.0f})"
                   r"$\pi/N$")
    ax.set_ylabel(ylabel)
    if args.xlim is not None:
        ax.set_xlim(*args.xlim)
    if args.xlog:
        ax.set_xscale('log')
    if args.ylim is not None:
        ax.set_ylim(*args.ylim)
    if args.ylog:
        ax.set_yscale('log')
    ax.legend()
    fig.tight_layout()

    if args.output is not None:
        fig.savefig(args.output)
    else:
        plt.show()


if __name__ == "__main__":
    main()
