#!/usr/bin/env python3
"""Plot the time correlator sum_T jpx(t)*jpx(t+T) as a function of the time
difference t, averaged over several runs with an error band from their
run-to-run variation.

Reads the per-run correlator files written by compute_jpx_time_correlator.py:
one <run>.dat file per run in --input-dir, with columns time_diff, Re, Im and
a header recording nx, ny, nz, nkx, nky, nkz, dt for the given mode.

--input-dir is expected to be named as generated by
compute_jpx_time_correlator.py, e.g. avg-jp-time-corr-Nx8Ny8Nz8dt0.1eta0.1Lam1.25 (with an
optional trailing "x" for --no-ideal-step runs); the shear viscosity eta is
parsed from that name."""

import argparse
import re
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

FLOAT = r"[0-9.]+(?:[eE][+-]?[0-9]+)?"
OBS_NAME_RE = re.compile(
    rf"avg-jp-time-corr-Nx(?P<nx>\d+)Ny(?P<ny>\d+)Nz(?P<nz>\d+)"
    rf"dt(?P<dt>{FLOAT})eta(?P<eta>{FLOAT})Lam(?P<lam>{FLOAT})(?P<suffix>x?)$"
)


def parse_obs_name(input_dir: Path) -> dict:
    m = OBS_NAME_RE.match(input_dir.name)
    if m is None:
        raise SystemExit(f"Cannot parse input directory name '{input_dir.name}': "
                         "expected the form avg-jp-time-corr-Nx8Ny8Nz8dt0.1eta0.1Lam1.25")
    return {"nx": int(m["nx"]), "ny": int(m["ny"]), "nz": int(m["nz"]),
            "dt": float(m["dt"]), "eta": float(m["eta"]), "lam": float(m["lam"])}


def read_header(path: Path) -> dict:
    with open(path) as f:
        first_line = f.readline().lstrip("#").strip()
    return {key: float(value) for key, value in
            (item.split("=") for item in first_line.split())}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input_dir", type=Path,
                         help="Directory containing the *.dat correlator files "
                              "written by compute_jpx_time_correlator.py, named "
                              "like avg-jp-time-corr-Nx8Ny8Nz8dt0.1eta0.1Lam1.25 (eta is "
                              "parsed from the name)")
    parser.add_argument("--mass-density", type=float, default=1.0, help="Mass density")
    parser.add_argument("--temp", type=float, default=1.0, help="Temperature")
    parser.add_argument("-o", "--output", type=Path, default=None,
                         help="Save the plot to this file instead of showing it")
    parser.add_argument("--xlim", type=float, nargs=2, default=None,
                         metavar=("XMIN", "XMAX"),
                         help="x-axis limits of the plot")
    parser.add_argument("--ylim", type=float, nargs=2, default=None,
                         metavar=("YMIN", "YMAX"),
                         help="y-axis limits of the plot")
    parser.add_argument("--xlog", action="store_true",
                         help="Use a logarithmic x-axis")
    parser.add_argument("--ylog", action="store_true",
                         help="Use a logarithmic y-axis")
    args = parser.parse_args()

    obs_name = parse_obs_name(args.input_dir)
    eta = obs_name["eta"]
    lam = obs_name["lam"]

    paths = sorted(args.input_dir.glob("*.dat"))
    if not paths:
        raise SystemExit(f"No correlator files found in {args.input_dir}")

    meta = read_header(paths[0])

    correlators = []
    time_diff = None
    for path in paths:
        t, re, im = np.loadtxt(path, unpack=True)
        if time_diff is None:
            time_diff = t
        correlators.append(re + 1j * im)

    n_min = min(len(c) for c in correlators)
    correlators = np.stack([c[:n_min] for c in correlators])
    time_diff = time_diff[:n_min]

    mean = correlators.mean(axis=0)
    n_runs = len(correlators)
    if n_runs > 1:
        # Standard error of the mean, not the run-to-run standard deviation:
        # the latter reflects the spread from the Langevin noise itself and
        # does not shrink as more runs are added, while the SEM quantifies
        # the uncertainty on the estimated mean correlator.
        sem_re = correlators.real.std(axis=0, ddof=1) / np.sqrt(n_runs)
        sem_im = correlators.imag.std(axis=0, ddof=1) / np.sqrt(n_runs)
    else:
        sem_re = np.zeros(n_min)
        sem_im = np.zeros(n_min)

    k_hat = 2.0*np.sin(2 * np.pi * meta["nk"] / meta["nx"] * 0.5)
    damp = eta / args.mass_density * k_hat**2

    nsites = meta["nx"] * meta["ny"] * meta["nz"]
    theory =  args.temp * args.mass_density* np.exp(-damp * time_diff)

    coeff = 0.0236416
    etaR = np.sqrt(eta**2 + 2.0*coeff*args.temp*args.mass_density*lam)
    print("Renormalized eta: ", eta, " -> ", etaR)

    dampR = etaR / args.mass_density * k_hat**2

    theoryR =  args.temp * args.mass_density* np.exp(-dampR * time_diff)

    fig, ax = plt.subplots()
    for part, values, errors in (("Re", mean.real, sem_re), ("Im", mean.imag, sem_im)):
        line, = ax.plot(time_diff, values/nsites, label=part)
        ax.fill_between(time_diff, (values - errors)/nsites, (values + errors)/nsites,
                         color=line.get_color(), alpha=0.3)
    ax.plot(time_diff, theory, "--", color="red",
            label=r"$\exp(-(\eta/\rho) \, \hat{\mathbf{k}}^2\, t)$")
    ax.plot(time_diff, theoryR, "--", color="black",
            label=r"$\exp(-(\eta_R/\rho) \, \hat{\mathbf{k}}^2\, t)$")
    ax.set_xlabel(r"$t$")
    ax.set_ylabel(r"$\frac{1}{T}\sum_T \frac{1}{6}\sum_{l \neq m} \langle j_{l}^{*}(T+t,k\mathbf{e}_m) j_{l}(T,k\mathbf{e}_m)\rangle$,  $k=$"
                  f"{meta['nk']:.0f}"
                  r"$\pi/N$")
                  #f"(nkx={meta['nkx']:.0f}, nky={meta['nky']:.0f}, nkz={meta['nkz']:.0f})")
    if args.xlim is not None:
        ax.set_xlim(*args.xlim)
    if args.xlog:
        ax.set_xscale('log')
    if args.ylim is not None:
        ax.set_ylim(*args.ylim)
    if args.ylog:
        ax.set_yscale('log')
    # ax.set_ylim(1e-4, 1e1)
    # ax.set_ylim(-0.2*theory[0], 1.2*theory[0])
    ax.legend()
    fig.tight_layout()

    if args.output is not None:
        fig.savefig(args.output)
    else:
        plt.show()


if __name__ == "__main__":
    main()
