#!/usr/bin/env python3
"""Plot the logarithmic time derivative d ln f(t)/dt = f'(t)/f(t) of the real
part f(t) of the time correlator sum_T jpx(t)*jpx(t+T) as a function of the
time difference t, averaged over several runs with an error band from their
run-to-run variation. For an exponential decay f(t) ~ exp(-Gamma t) this is
the constant -Gamma. Only meaningful at small t, before f(t) decays into the
noise; restrict the view with --xlim/--ylim.

Reads the per-run correlator files written by compute_jpx_time_correlator.py:
one <run>.dat file per run in --input-dir, with columns time_diff, Re, Im and
a header recording nx, ny, nz, nkx, nky, nkz, dt for the given mode.

Each input directory is expected to be named as generated by
compute_jpx_time_correlator.py, e.g. avg-jp-time-corr-Nx8Ny8Nz8dt0.1eta0.1Lam1.25nk7 (with
an optional trailing "x" for --no-ideal-step runs); the shear viscosity eta
is parsed from that name. With several directories, the log-derivatives of
all of them are drawn into the same plot. For each directory the fit window
etaR_fit.py measures etaR over, [tau, 2 tau] with tau solved for from the data
by the self-consistency condition tau = 1/dampR(tau), is marked by two
vertical lines; the same window in t lands at a different place on the scaled
axis for every eta and k, so each directory gets its own pair. With
--show-fit the result of that fit is drawn as a horizontal line as well.
A directory whose correlator is sampled too coarsely, or run too briefly, for
the condition to have a solution is still plotted: it loses its window and its
fit, with a warning, not the figure.

The t axis is scaled by the bare correlation time of the mode,
tau = rho/(eta (1+eta_reg_uv) k_hat^2), so that the bare exponential decay
reaches 1/e at t/tau = 1 for every eta and k and curves from different
directories can be compared directly. Time arguments (fit and plateau
windows) stay in units of t; only the axis is scaled."""

import argparse
import re
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

import plot_style
import etaR_fit

plot_style.use()

AUTO_OUTPUT = Path("<auto>")

FLOAT = r"[0-9.]+(?:[eE][+-]?[0-9]+)?"
OBS_NAME_RE = re.compile(
    rf"avg-jp-time-corr-Nx(?P<nx>\d+)Ny(?P<ny>\d+)Nz(?P<nz>\d+)"
    rf"dt(?P<dt>{FLOAT})eta(?P<eta>{FLOAT})Lam(?P<lam>{FLOAT})nk(?P<nk>\d+)(?P<suffix>x?)$"
)


def parse_obs_name(input_dir: Path) -> dict:
    m = OBS_NAME_RE.match(input_dir.name)
    if m is None:
        raise SystemExit(f"Cannot parse input directory name '{input_dir.name}': "
                         "expected the form avg-jp-time-corr-Nx8Ny8Nz8dt0.1eta0.1Lam1.25nk7")
    return {"nx": int(m["nx"]), "ny": int(m["ny"]), "nz": int(m["nz"]),
            "dt": float(m["dt"]), "eta": float(m["eta"]), "lam": float(m["lam"]),
            "nk": int(m["nk"])}


def lattice_label(nx: int, ny: int, nz: int) -> str:
    r"""LaTeX for the lattice size: $32^3$ for a cubic lattice, $32^2 \times 10$
    when one direction differs from the two others."""
    dims = (nx, ny, nz)
    if nx == ny == nz:
        return rf"${nx}^3$"
    for d in dims:
        if dims.count(d) == 2:
            odd = next(o for o in dims if o != d)
            return rf"${d}^2 \times {odd}$"
    return rf"${nx} \times {ny} \times {nz}$"


def label_hline(axis, y, text, color, x=0.01, below=False):
    """Label a horizontal line next to the line itself instead of in the
    legend: at the left edge of the axes, just above (or below) the line.
    x is a fraction of the axes width, y a data coordinate."""
    axis.annotate(text, xy=(x, y), xycoords=axis.get_yaxis_transform(),
                  xytext=(0, -3 if below else 3), textcoords="offset points",
                  ha="left" if x < 0.5 else "right",
                  va="top" if below else "bottom",
                  color=color, fontsize="small", zorder=6)


def label_vline(axis, x, text, color, y=0.02, on_left=True):
    """Label a vertical theory line next to the line itself instead of in the
    legend: rotated along the line, near the bottom of the axes, on its
    right (on_left) or on its left. x is a data coordinate, y a fraction
    of the axes height."""
    # Above the legend (zorder 5): these labels sit at the bottom of the
    # axes, where the legend often lands, and a hidden label is worse than
    # one that crosses the legend box.
    axis.annotate(text, xy=(x, y), xycoords=axis.get_xaxis_transform(),
                  xytext=(5, 0) if on_left else (-5, 0), textcoords="offset points", rotation=90,
                  ha="left" if on_left else "right", va="bottom",
                  color=color, fontsize="small", zorder=6)


def legend_label(input_dir: Path, with_nk: bool = False) -> str:
    r"""Legend entry for one directory, e.g.
    "$32^3$, dt = 10, $\eta = 0.0707107$, $\Lambda = 0.4$".

    The numbers are taken verbatim from the directory name, so the legend
    shows exactly what the run used. The mode index is appended only when
    asked for, i.e. when the directories do not share one and the y label
    cannot carry it, and --no-ideal-step runs are marked as such; without
    that two directories differing only in nk (or in the trailing "x") would
    get the same legend entry."""
    m = OBS_NAME_RE.match(input_dir.name)
    label = (f"{lattice_label(int(m['nx']), int(m['ny']), int(m['nz']))}, "
             #f"dt = {m['dt']}, "
             rf"$\eta = {m['eta']}$, $a\Lambda = {m['lam']}$")
    if with_nk:
        label += rf", $n_k = {m['nk']}$"
    if m["suffix"] == "x":
        label += ", no ideal step"
    return label


def read_header(path: Path) -> dict:
    with open(path) as f:
        first_line = f.readline().lstrip("#").strip()
    return {key: float(value) for key, value in
            (item.split("=") for item in first_line.split())}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input_dirs", type=Path, nargs="+",
                         help="One or more directories containing the *.dat correlator "
                              "files written by compute_jpx_time_correlator.py, named "
                              "like avg-jp-time-corr-Nx8Ny8Nz8dt0.1eta0.1Lam1.25nk7 (eta is "
                              "parsed from the name); all are drawn into the same plot")
    parser.add_argument("--mass-density", type=float, default=1.0, help="Mass density")
    parser.add_argument("--temp", type=float, default=1.0, help="Temperature")
    parser.add_argument("--show-fit", action="store_true",
                         help="Fit etaR over the marked window by the standard "
                              "procedure in etaR_fit.py, print it and draw the "
                              "fitted rate as a horizontal line in the "
                              "directory's own color")
    parser.add_argument("--plateau-window", type=float, nargs=2, default=None,
                         metavar=("T1", "T2"),
                         help="Average the log-derivative per run over this time "
                              "window (chosen where the curve is flat: after the "
                              "early transient, before the correlator decays into "
                              "the noise), convert it to the renormalized shear "
                              "viscosity etaR = -<dln Re/dt>/(k_hat^2 "
                              "(1+eta_reg_uv)/rho), print etaR +- SEM, and draw "
                              "the window and plateau level in the plot; given "
                              "in units of t, not of the scaled x axis")
    parser.add_argument("-o", "--output", type=Path, nargs="?", default=None,
                         const=AUTO_OUTPUT,
                         help="Save the plot to this file instead of showing it; "
                              "without an argument, save to figs/<first-input-dir-name>.pdf "
                              "(with -cmp<n> appended when several input dirs are given)")
    parser.add_argument("--xlim", type=float, nargs=2, default=None,
                         metavar=("XMIN", "XMAX"),
                         help="x-axis limits of the plot, in units of the bare "
                              "correlation time")
    parser.add_argument("--ylim", type=float, nargs=2, default=None,
                         metavar=("YMIN", "YMAX"),
                         help="y-axis limits of the plot, in units of the bare "
                              "damping rate 1/tau (the bare theory sits at -1)")
    parser.add_argument("--xlog", action="store_true",
                         help="Use a logarithmic x-axis")
    parser.add_argument("--ylog", action="store_true",
                         help="Use a logarithmic y-axis")
    args = parser.parse_args()

    if args.output is AUTO_OUTPUT:
        stem = args.input_dirs[0].name.replace("avg-jp-time-corr-", "avg-jp-time-corr-deriv-")
        if len(args.input_dirs) > 1:
            stem += f"-cmp{len(args.input_dirs) - 1}"
        args.output = Path("figs") / f"{stem}.pdf"
        args.output.parent.mkdir(exist_ok=True)

    # The mode index goes into the legend only when the y label
    # cannot carry it, i.e. when the directories do not share one.
    nk_varies = len({parse_obs_name(d)['nk']
                     for d in args.input_dirs}) > 1
    fig, ax = plt.subplots()
    nks = []
    plateau_spans = []
    for input_dir in args.input_dirs:
        obs_name = parse_obs_name(input_dir)
        eta = obs_name["eta"]
        lam = obs_name["lam"]

        paths = sorted(input_dir.glob("*.dat"))
        if not paths:
            raise SystemExit(f"No correlator files found in {input_dir}")

        meta = read_header(paths[0])
        nks.append(meta["nk"])

        def eta_reg_uv(k2):
            x = k2/(lam*lam)
            if x > 1:
                return x - 1
            else:
                return 0

        k_hat = 2.0*np.sin(2 * np.pi * meta["nk"] / meta["nx"] * 0.5)
        damp_per_eta = (1+eta_reg_uv(k_hat**2)) / args.mass_density * k_hat**2
        damp = eta * damp_per_eta
        # The time axis is scaled by the bare correlation time of the mode,
        # tau_bare = 1/damp = rho/(eta (1+eta_reg_uv) k_hat^2), so that the
        # bare exponential decays as exp(-t/tau_bare) whatever eta and k are.
        tau_bare = 1.0/damp

        # Per-run log-derivative f'/f, then mean and SEM across runs. Only valid
        # at small t: once a run's f(t) decays into the noise and crosses zero,
        # its f'/f blows up and mean and SEM become meaningless.
        correlators = []
        log_derivatives = []
        time_diff = None
        for path in paths:
            t, re_part, im_part = np.loadtxt(path, unpack=True)
            if time_diff is None:
                time_diff = t
            correlators.append(re_part)
            log_derivatives.append(np.gradient(re_part, t) / re_part)

        n_min = min(len(d) for d in log_derivatives)
        log_derivatives = np.stack([d[:n_min] for d in log_derivatives])
        correlators = np.stack([c[:n_min] for c in correlators])
        time_diff = time_diff[:n_min]

        # The curve stops at the first zero-crossing of the correlator, where
        # f'/f has a pole: only the contiguous stretch at the start over which
        # every run is still positive is kept, the same criterion etaR_fit.py
        # applies to its fit window. Beyond that crossing the run has decayed
        # into the noise, and its log-derivative diverges and then wanders
        # about, dragging mean and SEM with it whether the points that follow
        # happen to be positive or not.
        positive = np.all(correlators > 0, axis=0)
        crossings = np.flatnonzero(~positive)
        if crossings.size:
            n_keep = crossings[0]
            if n_keep == 0:
                raise SystemExit(f"{input_dir.name}: the correlator is "
                                 "non-positive at the first time difference; "
                                 "nothing to plot")
            print(f"{input_dir.name}: correlator crosses zero at "
                  f"t = {time_diff[n_keep]:g}, plotting up to "
                  f"t = {time_diff[n_keep - 1]:g}")
            log_derivatives = log_derivatives[:, :n_keep]
            time_diff = time_diff[:n_keep]
            n_min = n_keep
        t_scaled = time_diff/tau_bare

        mean = log_derivatives.mean(axis=0)
        n_runs = len(log_derivatives)
        if n_runs > 1:
            sem = log_derivatives.std(axis=0, ddof=1) / np.sqrt(n_runs)
        else:
            sem = np.zeros(n_min)

        label = legend_label(input_dir, with_nk=nk_varies)
        # The log-derivative is scaled by the same tau_bare as the time
        # axis, so it is d ln f/d(t/tau_bare): the bare rate sits at -1 and
        # the renormalized one at -etaR/eta, whatever eta and k are.
        line, = ax.plot(t_scaled, mean*tau_bare, label=label)
        ax.fill_between(t_scaled, (mean - sem)*tau_bare, (mean + sem)*tau_bare,
                         color=line.get_color(), alpha=0.3)

        # The window etaR_fit.py fits etaR over, [TMIN_FACTOR, TMAX_FACTOR]
        # tau, as two vertical lines. Gray, like the window in
        # plot_avg_jp_time_correlator_deriv_fit.py and for the same reason:
        # the windows of different directories nearly coincide and would
        # otherwise blend into a color belonging to none of them.
        window_color = "gray"
        # The window scale tau follows from the self-consistency condition
        # tau = 1/dampR(tau) and so from the fit itself, not from theory:
        # the fit is run for every directory, whether or not --show-fit
        # draws its result, and the window it used is what is marked here.
        # This is a plotting script, though, and the data is worth looking at
        # even where the condition has no solution -- a mode sampled too
        # coarsely in time to resolve its own decay, say, which is exactly
        # what one wants to see in the plot -- so a failure costs this
        # directory its window and its fit, not the whole figure.
        try:
            fit = etaR_fit.fit_etaR(input_dir, mass_density=args.mass_density,
                                    temp=args.temp)
        except SystemExit as exc:
            print(f"no fit window for {input_dir.name}: {exc}")
            fit = None
        if fit is not None:
            for bound in (fit.fit_tmin, fit.fit_tmax):
                ax.axvline(bound/tau_bare, linestyle=":", color=window_color,
                           alpha=0.7)
            # The lower bound is the correlation time the fit itself yields,
            # tau_R = 1/dampR, since that is what the self-consistency
            # condition tau = 1/dampR(tau) fixes; on the axis, scaled by the
            # bare correlation time, it sits at tau_R/tau. Labelling it makes
            # the condition readable off the plot: the window starts where
            # the fitted rate below says it should.
            # Both labels on the left of their line, a whole tau_R/tau
            # apart, which keeps them off each other and off the legend the
            # upper bound would otherwise run into.
            label_vline(ax, fit.fit_tmin/tau_bare, r"$\tau_R/\tau$",
                        window_color, on_left=False)
            # label_vline(ax, fit.fit_tmax/tau_bare, r"$2\tau_R/\tau$",
            #             window_color, on_left=False)
            # The second pass, the same window half a tau later, whose
            # difference from the first is the systematic. It solves the same
            # condition over its own window, so it has a correlation time
            # tau_R' of its own and its window is [1.5, 2.5] tau_R'. Dash-dot
            # against the dotted first window: the two pairs interleave and
            # must be told apart at a glance.
            if fit.etaR_alt is not None:
                for bound in (fit.fit_tmin_alt, fit.fit_tmax_alt):
                    ax.axvline(bound/tau_bare, linestyle="-.",
                               color=window_color, alpha=0.5)
                label_vline(ax, fit.fit_tmin_alt/tau_bare,
                            r"$1.5\tau_R'/\tau$", window_color,
                            on_left=False)
                # label_vline(ax, fit.fit_tmax_alt/tau_bare,
                #             r"$2.5\tau_R'/\tau$", window_color,
                #             on_left=False)

        if args.show_fit and fit is not None:
            # The standard fit, over exactly the window marked above; the
            # rate is scaled by the same tau_bare as the data, so the line
            # sits at -etaR/eta whatever eta and k are.
            print(fit.summary())
            # Only the statistical error is quoted. The systematic is the
            # difference between this fit and the second one, and both are
            # drawn: it is the gap between the two horizontal lines, which
            # says more in the plot than a number in the legend. It is still
            # printed by fit.summary() above.
            fit_label = (r"$\eta_R = $" f"{fit.etaR:.4g}"
                         r"$\,\pm\,$" f"{fit.stat:.2g}" r"$_{\mathrm{stat}}$")
            ax.axhline(-fit.dampR*tau_bare, linestyle="--",
                       color=line.get_color(), label=fit_label)
            # The second fit, drawn like its window: the gap between the two
            # horizontal lines is the systematic the legend quotes.
            if fit.etaR_alt is not None:
                dampR_alt = fit.etaR_alt*damp_per_eta
                ax.axhline(-dampR_alt*tau_bare, linestyle="-.",
                           color=line.get_color(), alpha=0.6,
                           label=r"$\eta_R' = $" f"{fit.etaR_alt:.4g}"
                                 r"$\,\pm\,$" f"{fit.stat_alt:.2g}"
                                 r"$_{\mathrm{stat}}$")
            # The fitted rate is -1/tau_R with the same tau_R the window
            # starts at, which is the whole content of the self-consistency
            # condition; scaled by the bare correlation time like the axis
            # it is -tau/tau_R, the reciprocal of where the window begins.
            # The two rates differ by the systematic, so their lines can be a
            # hair apart: each label goes on the outward side of its own line,
            # the upper one above and the lower one below, so that they never
            # end up between the lines or on top of each other. With no
            # second pass the single label goes below, where the data at the
            # left edge is still above the line, coming down out of the
            # transient.
            if fit.etaR_alt is None:
                first_below = True
            else:
                first_below = fit.dampR > dampR_alt
                label_hline(ax, -dampR_alt*tau_bare, r"$-\tau/\tau_R'$",
                            line.get_color(), below=not first_below)
            label_hline(ax, -fit.dampR*tau_bare, r"$-\tau/\tau_R$",
                        line.get_color(), below=first_below)

        if args.plateau_window is not None:
            t1, t2 = args.plateau_window
            sel = (time_diff >= t1) & (time_diff <= t2)
            if not sel.any():
                raise SystemExit(f"Plateau window [{t1}, {t2}] contains no "
                                 f"data points of {input_dir.name}")

            # Average the local rate per run over the window, then mean and
            # SEM across runs, so the error includes the correlated noise.
            per_run = log_derivatives[:, sel].mean(axis=1)
            rate = per_run.mean()
            if n_runs > 1:
                rate_sem = per_run.std(ddof=1) / np.sqrt(n_runs)
            else:
                rate_sem = 0.0
            etaR = -rate / damp_per_eta
            etaR_err = rate_sem / damp_per_eta
            print(f"{input_dir.name}: plateau [{t1:g}, {t2:g}]: "
                  f"etaR = {etaR:g} +- {etaR_err:g} (bare eta = {obs_name['eta']:g})")

            plateau_spans.append((t1/tau_bare, t2/tau_bare))
            # The window is hand-picked here, so there is no second pass to
            # compare against and no systematic: the error is statistical
            # only, and is labelled as such to match the fit legend above.
            ax.hlines(rate*tau_bare, t1/tau_bare, t2/tau_bare, color=line.get_color(),
                      linestyle="--",
                      label=r"$\eta_R = $" f"{etaR:.4g}"
                            r"$\,\pm\,$" f"{etaR_err:.2g}"
                            r"$_{\mathrm{stat}}$")

    # One span per directory: the same window in t is a different window in
    # t/tau_bare for every eta and k. Identical spans are drawn only once.
    for span in dict.fromkeys(plateau_spans):
        ax.axvspan(*span, color="gray", alpha=0.1, zorder=0)

    ax.set_xlabel(r"$\Delta t / \tau$,  $\tau = \rho/(\eta \hat{\mathbf{k}}^2)$")
    #ylabel = r"$\tau\,\partial_t \ln \mathrm{Re}\,\frac{1}{T}\sum_T \frac{1}{12}\sum_{l \neq m} \sum_{\pm} \langle j_{l}^{*}(T+t,\pm k\mathbf{e}_m) j_{l}(T,\pm k\mathbf{e}_m)\rangle$"
    if len(set(nks)) == 1:
        ylabel = r"$\tau\,\partial \ln C(\Delta t,k=$" f"{nks[0]:.0f}" r"$\pi/N)/\partial \Delta t$"
    else:
        ylabel = r"$\tau\,\partial \ln C(\Delta t)/\partial \Delta t$"
    ax.set_ylabel(ylabel)
    if args.xlim is not None:
        ax.set_xlim(*args.xlim)
    if args.xlog:
        ax.set_xscale('log')
    if args.ylim is not None:
        ax.set_ylim(*args.ylim)
    if args.ylog:
        ax.set_yscale('log')
    # A fixed corner rather than "best": the theory labels sit inside the
    # plot, at the axes edges, and an automatically placed legend would
    # sooner or later be dropped on top of them.
    ax.legend(loc="lower right")
    fig.tight_layout(pad=0.2)

    if args.output is not None:
        fig.savefig(args.output)
    else:
        plt.show()


if __name__ == "__main__":
    main()
