#!/usr/bin/env python3
"""Plot the logarithmic time derivative d ln f(t)/dt = f'(t)/f(t) of the real
part f(t) of the time correlator sum_T jpx(t)*jpx(t+T) as a function of the
time difference t, averaged over several runs with an error band from their
run-to-run variation. For an exponential decay f(t) ~ exp(-Gamma t) this is
the constant -Gamma. Only meaningful at small t, before f(t) decays into the
noise; restrict the view with --xlim/--ylim.

Reads the per-run correlator files written by compute_jpx_time_correlator.py:
one <run>.dat file per run in --input-dir, with columns time_diff, Re, Im and
a header recording nx, ny, nz, nkx, nky, nkz, dt for the given mode.

Each input directory is expected to be named as generated by
compute_jpx_time_correlator.py, e.g. avg-jp-time-corr-Nx8Ny8Nz8dt0.1eta0.1Lam1.25nk7 (with
an optional trailing "x" for --no-ideal-step runs); the shear viscosity eta
is parsed from that name. With several directories, the log-derivatives of
all of them are drawn into the same plot. For each directory the theory
expectation is drawn as two horizontal lines, -(eta/rho)(1+eta_reg_uv)k_hat^2
with the bare (dashed) and the renormalized (dotted) shear viscosity, and the
corresponding correlation times 1/Gamma as two vertical lines."""

import argparse
import re
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

AUTO_OUTPUT = Path("<auto>")

FLOAT = r"[0-9.]+(?:[eE][+-]?[0-9]+)?"
OBS_NAME_RE = re.compile(
    rf"avg-jp-time-corr-Nx(?P<nx>\d+)Ny(?P<ny>\d+)Nz(?P<nz>\d+)"
    rf"dt(?P<dt>{FLOAT})eta(?P<eta>{FLOAT})Lam(?P<lam>{FLOAT})nk(?P<nk>\d+)(?P<suffix>x?)$"
)


def parse_obs_name(input_dir: Path) -> dict:
    m = OBS_NAME_RE.match(input_dir.name)
    if m is None:
        raise SystemExit(f"Cannot parse input directory name '{input_dir.name}': "
                         "expected the form avg-jp-time-corr-Nx8Ny8Nz8dt0.1eta0.1Lam1.25nk7")
    return {"nx": int(m["nx"]), "ny": int(m["ny"]), "nz": int(m["nz"]),
            "dt": float(m["dt"]), "eta": float(m["eta"]), "lam": float(m["lam"]),
            "nk": int(m["nk"])}


def read_header(path: Path) -> dict:
    with open(path) as f:
        first_line = f.readline().lstrip("#").strip()
    return {key: float(value) for key, value in
            (item.split("=") for item in first_line.split())}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input_dirs", type=Path, nargs="+",
                         help="One or more directories containing the *.dat correlator "
                              "files written by compute_jpx_time_correlator.py, named "
                              "like avg-jp-time-corr-Nx8Ny8Nz8dt0.1eta0.1Lam1.25nk7 (eta is "
                              "parsed from the name); all are drawn into the same plot")
    parser.add_argument("--mass-density", type=float, default=1.0, help="Mass density")
    parser.add_argument("--temp", type=float, default=1.0, help="Temperature")
    parser.add_argument("--plateau-window", type=float, nargs=2, default=None,
                         metavar=("T1", "T2"),
                         help="Average the log-derivative per run over this time "
                              "window (chosen where the curve is flat: after the "
                              "early transient, before the correlator decays into "
                              "the noise), convert it to the renormalized shear "
                              "viscosity etaR = -<dln Re/dt>/(k_hat^2 "
                              "(1+eta_reg_uv)/rho), print etaR +- SEM, and draw "
                              "the window and plateau level in the plot")
    parser.add_argument("-o", "--output", type=Path, nargs="?", default=None,
                         const=AUTO_OUTPUT,
                         help="Save the plot to this file instead of showing it; "
                              "without an argument, save to figs/<first-input-dir-name>.pdf "
                              "(with -cmp<n> appended when several input dirs are given)")
    parser.add_argument("--xlim", type=float, nargs=2, default=None,
                         metavar=("XMIN", "XMAX"),
                         help="x-axis limits of the plot")
    parser.add_argument("--ylim", type=float, nargs=2, default=None,
                         metavar=("YMIN", "YMAX"),
                         help="y-axis limits of the plot")
    parser.add_argument("--xlog", action="store_true",
                         help="Use a logarithmic x-axis")
    parser.add_argument("--ylog", action="store_true",
                         help="Use a logarithmic y-axis")
    args = parser.parse_args()

    if args.output is AUTO_OUTPUT:
        stem = args.input_dirs[0].name.replace("avg-jp-time-corr-", "avg-jp-time-corr-deriv-")
        if len(args.input_dirs) > 1:
            stem += f"-cmp{len(args.input_dirs) - 1}"
        args.output = Path("figs") / f"{stem}.pdf"
        args.output.parent.mkdir(exist_ok=True)

    single = len(args.input_dirs) == 1
    fig, ax = plt.subplots()
    nks = []
    for input_dir in args.input_dirs:
        obs_name = parse_obs_name(input_dir)
        eta = obs_name["eta"]
        lam = obs_name["lam"]

        paths = sorted(input_dir.glob("*.dat"))
        if not paths:
            raise SystemExit(f"No correlator files found in {input_dir}")

        meta = read_header(paths[0])
        nks.append(meta["nk"])

        def eta_reg_uv(k2):
            x = k2/(lam*lam)
            if x > 1:
                return x - 1
            else:
                return 0

        k_hat = 2.0*np.sin(2 * np.pi * meta["nk"] / meta["nx"] * 0.5)
        damp_per_eta = (1+eta_reg_uv(k_hat**2)) / args.mass_density * k_hat**2
        damp = eta * damp_per_eta

        coeff = 0.0236416
        etaR = np.sqrt(eta**2 + 2.0*coeff*args.temp*args.mass_density*lam)
        dampR = etaR * damp_per_eta

        # Per-run log-derivative f'/f, then mean and SEM across runs. Only valid
        # at small t: once a run's f(t) decays into the noise and crosses zero,
        # its f'/f blows up and mean and SEM become meaningless.
        log_derivatives = []
        time_diff = None
        for path in paths:
            t, re_part, im_part = np.loadtxt(path, unpack=True)
            if time_diff is None:
                time_diff = t
            log_derivatives.append(np.gradient(re_part, t) / re_part)

        n_min = min(len(d) for d in log_derivatives)
        log_derivatives = np.stack([d[:n_min] for d in log_derivatives])
        time_diff = time_diff[:n_min]

        mean = log_derivatives.mean(axis=0)
        n_runs = len(log_derivatives)
        if n_runs > 1:
            sem = log_derivatives.std(axis=0, ddof=1) / np.sqrt(n_runs)
        else:
            sem = np.zeros(n_min)

        if single:
            label = r"$\partial_t \ln \mathrm{Re}$"
        else:
            label = input_dir.name.removeprefix("avg-jp-time-corr-")
        line, = ax.plot(time_diff, mean, label=label)
        ax.fill_between(time_diff, mean - sem, mean + sem,
                         color=line.get_color(), alpha=0.3)

        first = input_dir is args.input_dirs[0]
        theory_color = "red" if single else line.get_color()
        theoryR_color = "black" if single else line.get_color()
        ax.axhline(-damp, linestyle="--", color=theory_color, alpha=0.7,
                   label=r"$-(\eta/\rho) \, \hat{\mathbf{k}}^2$"
                         if single or first else None)
        ax.axhline(-dampR, linestyle=":", color=theoryR_color, alpha=0.7,
                   label=r"$-(\eta_R/\rho) \, \hat{\mathbf{k}}^2$"
                         if single or first else None)
        ax.axvline(1.0/damp, linestyle="--", color=theory_color, alpha=0.7,
                   label=r"$\rho/(\eta \hat{\mathbf{k}}^2)$"
                         if single or first else None)
        ax.axvline(1.0/dampR, linestyle=":", color=theoryR_color, alpha=0.7,
                   label=r"$\rho/(\eta_R \hat{\mathbf{k}}^2)$"
                         if single or first else None)

        if args.plateau_window is not None:
            t1, t2 = args.plateau_window
            sel = (time_diff >= t1) & (time_diff <= t2)
            if not sel.any():
                raise SystemExit(f"Plateau window [{t1}, {t2}] contains no "
                                 f"data points of {input_dir.name}")

            # Average the local rate per run over the window, then mean and
            # SEM across runs, so the error includes the correlated noise.
            per_run = log_derivatives[:, sel].mean(axis=1)
            rate = per_run.mean()
            if n_runs > 1:
                rate_sem = per_run.std(ddof=1) / np.sqrt(n_runs)
            else:
                rate_sem = 0.0
            etaR = -rate / damp_per_eta
            etaR_err = rate_sem / damp_per_eta
            print(f"{input_dir.name}: plateau [{t1:g}, {t2:g}]: "
                  f"etaR = {etaR:g} +- {etaR_err:g} (bare eta = {obs_name['eta']:g})")

            ax.hlines(rate, t1, t2, color=line.get_color(), linestyle="--",
                      label=r"$\eta_R = $" f"{etaR:.4g}"
                            r"$\,\pm\,$" f"{etaR_err:.2g}")

    if args.plateau_window is not None:
        ax.axvspan(*args.plateau_window, color="gray", alpha=0.1, zorder=0)

    ax.set_xlabel(r"$t$")
    ylabel = r"$\partial_t \ln \mathrm{Re}\,\frac{1}{T}\sum_T \frac{1}{12}\sum_{l \neq m} \sum_{\pm} \langle j_{l}^{*}(T+t,\pm k\mathbf{e}_m) j_{l}(T,\pm k\mathbf{e}_m)\rangle$"
    if len(set(nks)) == 1:
        ylabel += r",  $k=$" f"{nks[0]:.0f}" r"$\pi/N$"
    ax.set_ylabel(ylabel)
    if args.xlim is not None:
        ax.set_xlim(*args.xlim)
    if args.xlog:
        ax.set_xscale('log')
    if args.ylim is not None:
        ax.set_ylim(*args.ylim)
    if args.ylog:
        ax.set_yscale('log')
    ax.legend()
    fig.tight_layout()

    if args.output is not None:
        fig.savefig(args.output)
    else:
        plt.show()


if __name__ == "__main__":
    main()
